### PR TITLE
Adding possibility to update READ.me in QUAY.io registry.

### PR DESCRIPTION
**Pull request by zmiklank**
We need to figure out how the the quay.io tokens can be used for updating image descriptions.
Until then is this a WIP.

### CODE REVIEW

**Comment by zmiklank** [comment]
[Here](https://github.com/sclorg/nginx-container/pull/280) can be seen what changes will be needed in container repos.

**Comment by zmiklank** [comment]
A [script](https://github.com/adobes1/ci-scripts/blob/update_quay_description/jenkins_ci/update_quay_description.py) from @adobes1 has been used in this PR.

I have adjusted it a bit, and removed functionality for shortening READMEs. I have removed the shortening functionality because it was shortening the READMEs a lot and in the middle of the chapter, which made the descriptions less readable.
I can return it back, if needed.

**Comment by zmiklank** [comment]
@phracek PTAL.

**Review by phracek — APPROVED** [review]
LGTM. Let's see who this will work in real time

**Pull request merged**
