### PR TITLE
setup python before updating quay.io desc

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by phracek** [comment]
This is not the fix. It looks like the file does not exist.

```
python: can't open file 'update_quay_description.py': [Errno 2] No such file or directory
```

**Review by phracek — CHANGES_REQUESTED** [review]
Python is already properly set.

Based on the documentation
https://github.com/actions/setup-python

Add there:
```
  with:
    python-version: '3.11' 
```

**Comment by zmiklank** [comment]
Thanks for your review!

> Python is already properly set.

Are you sure? All the GitHub action I saw and used python scripts needed to use this
 setup action (or install Python.)
  
> Based on the documentation https://github.com/actions/setup-python
> 
> Add there:
> 
> ```
>   with:
>     python-version: '3.11' 
> ```

This parameter is optional.

Or we could install the python directly with apt.



> This is not the fix. It looks like the file does not exist.
> 
> ```
> python: can't open file 'update_quay_description.py': [Errno 2] No such file or directory
> ```

Yes, looks like that, you are right. But the file exists and is there.

**Comment by zmiklank** [comment]
Closing in favor of: https://github.com/sclorg/build-and-push-action/pull/36/.

**Pull request closed without merging**
